# Generated by Django 4.1.3 on 2022-11-13 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('points', models.PositiveSmallIntegerField(choices=[(0, 'TRIVIAL'), (1, 'BASIC'), (2, 'EASY'), (3, 'MEDIUM'), (5, 'HARD'), (8, 'TROLL')], default=2)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='subtask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('points', models.PositiveSmallIntegerField(choices=[(0, 'TRIVIAL'), (1, 'BASIC'), (2, 'EASY'), (3, 'MEDIUM'), (5, 'HARD'), (8, 'TROLL')], default=1)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailies.task')),
            ],
        ),
    ]
